### ISSUE TITLE
How to use 怎么用

### ISSUE THREAD

**Issue by kencom999** [L1nY4n/stock-tracker#1]
作者您好，A股送钱小助手请问如何使用，推送的股票有什么特征，能否讲解下谢谢？
Dear Author, could you explain the characteristics of the stock recommended? Thanks!

**Comment by L1nY4n** [comment]
@kencom999  就是一个桌面的小插件,设置里面以填股票代码的方式添加股票,设置一定的周期查询这些股票的实时数据(当前价格,涨跌、买5卖5等), 每个票子有两个图表可以查看,一个是买5卖5对比,一个是K线查看
It's  just a desktop widget , you can add stocks by entering their stock codes in the settings panel(via ⚙️) . The backend will query real-time data for these stocks(includes current price, price change, top 5 bids, top 5 asks, etc.). Each stock has two charts available for viewing: one for comparing the top 5 bids and asks, and another for  K line trending
